# Generated by Django 4.2.23 on 2025-08-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
