# Generated by Django 4.2.23 on 2025-08-19 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalid',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Digital ID', 'verbose_name_plural': 'Digital IDs'},
        ),
        migrations.AlterField(
            model_name='digitalid',
            name='id_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='digitalid',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='digitalid',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_id', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
